apiVersion: apps/v1
kind: Deployment
metadata:
  name: tavira-app
  namespace: default
  labels:
    app: tavira
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: tavira
  template:
    metadata:
      labels:
        app: tavira
        version: v1
    spec:
      # Security context for the pod
      securityContext:
        fsGroup: 82  # www-data group ID

      # Init container to copy application code
      initContainers:
        - name: copy-app
          image: ingmontoyav/tavira-app:latest
          command:
            - sh
            - -c
            - |
              cp -r /var/www/html/* /app-code/
              mkdir -p /app-code/storage/app/public
              mkdir -p /app-code/storage/framework/cache
              mkdir -p /app-code/storage/framework/sessions
              mkdir -p /app-code/storage/framework/views
              mkdir -p /app-code/storage/logs
              chmod -R 775 /app-code/storage
              chmod -R 755 /app-code/bootstrap/cache
          volumeMounts:
            - name: app-code
              mountPath: /app-code
          securityContext:
            runAsUser: 0
            runAsGroup: 0

      containers:
        # PHP-FPM Container
        - name: php-fpm
          image: ingmontoyav/tavira-app:latest
          imagePullPolicy: Always

          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP

          # Environment variables
          env:
            - name: APP_NAME
              value: "Tavira"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: APP_KEY
            - name: APP_URL
              value: "https://tavira.com.co"

            # Database configuration
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: DB_PASSWORD

            # Cache configuration
            - name: CACHE_DRIVER
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: CACHE_DRIVER
                  optional: true
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: REDIS_HOST
                  optional: true
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: REDIS_PORT
                  optional: true

            # Queue configuration
            - name: QUEUE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: QUEUE_CONNECTION
                  optional: true

            # Session configuration
            - name: SESSION_DRIVER
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_DRIVER
            - name: SESSION_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_LIFETIME
            - name: SESSION_ENCRYPT
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_ENCRYPT
            - name: SESSION_PATH
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_PATH
            - name: SESSION_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_DOMAIN
            - name: SESSION_SECURE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_SECURE_COOKIE
            - name: SESSION_SAME_SITE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SESSION_SAME_SITE

            # Mail configuration
            - name: MAIL_MAILER
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_MAILER
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_PASSWORD
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_FROM_ADDRESS
            - name: MAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_FROM_NAME
            - name: MAIL_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: MAIL_ENCRYPTION

            # Localization
            - name: APP_LOCALE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: APP_LOCALE
            - name: APP_FALLBACK_LOCALE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: APP_FALLBACK_LOCALE
            - name: APP_FAKER_LOCALE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: APP_FAKER_LOCALE

            # Security & CORS
            - name: SANCTUM_STATEFUL_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SANCTUM_STATEFUL_DOMAINS
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: CORS_ALLOWED_ORIGINS
            - name: TRUSTED_PROXIES
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: TRUSTED_PROXIES

            # Wompi Payment Gateway
            - name: WOMPI_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: WOMPI_PUBLIC_KEY
            - name: WOMPI_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: WOMPI_PRIVATE_KEY
            - name: WOMPI_PRIVATE_EVENT_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: WOMPI_PRIVATE_EVENT_KEY

            # Sentry Error Tracking
            - name: SENTRY_LARAVEL_DSN
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SENTRY_LARAVEL_DSN
            - name: SENTRY_SEND_DEFAULT_PII
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SENTRY_SEND_DEFAULT_PII
            - name: SENTRY_TRACES_SAMPLE_RATE
              valueFrom:
                secretKeyRef:
                  name: laravel-env
                  key: SENTRY_TRACES_SAMPLE_RATE

          # Volume mounts - shared with NGINX
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: app-storage
              mountPath: /var/www/html/storage

          # Resource limits
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # Liveness probe
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          # Security context
          securityContext:
            runAsUser: 82  # www-data user ID
            runAsGroup: 82
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

        # NGINX Container (Sidecar)
        - name: nginx
          image: nginx:1.26-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          # Volume mounts - shared with PHP-FPM
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run

          # Resource limits
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          # Liveness probe
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          # Security context
          securityContext:
            runAsUser: 101  # nginx user ID
            runAsGroup: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

      # Volumes
      volumes:
        - name: app-code
          emptyDir: {}
        - name: app-storage
          persistentVolumeClaim:
            claimName: tavira-storage-pvc
        - name: nginx-config
          configMap:
            name: tavira-nginx-config
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}

      # DNS policy
      dnsPolicy: ClusterFirst

      # Restart policy
      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tavira-storage-pvc
  namespace: default
  labels:
    app: tavira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # k3s default storage class
