apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-staging
  namespace: staging
  labels:
    app: postgres-staging
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi  # Reduced from 10Gi for staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tavira-storage-pvc-staging
  namespace: staging
  labels:
    app: tavira-staging
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi  # Reduced from 10Gi for staging
