apiVersion: v1
kind: Service
metadata:
  name: redis-staging
  namespace: default
  labels:
    app: redis-staging
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: redis-staging
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
