<?php

return [
    'basic' => [
        'name' => 'Plan Básico',
        'price' => 149000,
        'max_units' => 30,
        'features' => [
            // Core features
            'correspondence' => true,
            'announcements' => true,
            'support_tickets' => true,
            'apartment_management' => ['level' => 'basic'],
            'resident_management' => ['level' => 'basic'],
            'basic_administration' => true,
            'analytics_dashboard' => ['level' => 'basic'],
            'access_control' => ['level' => 'basic'],
            'system_configuration' => true,
            'push_notifications' => true,
            'documents' => ['storage_gb' => 1],

            // Marketplace básico
            'marketplace_providers' => [
                'enabled' => true,
                'access_level' => 'basic',
                'quotations_monthly' => 3,
                'commission_rate' => 0.08,
                'provider_directory' => true,
                'provider_ratings' => 'read_only',
                'direct_contact' => true,
                'payment_integration' => false,
                'quotation_comparison' => false,
            ],

            // Features NO incluidos
            'institutional_email' => false,
            'internal_messaging' => false,
            'maintenance_requests' => false,
            'visitor_management' => false,
            'financial_reports' => false,
            'expense_approvals' => false,
            'accounting' => false,
            'reservations' => false,
            'payment_agreements' => false,
            'meeting_minutes' => false,
            'voting' => false,
            'audit_logs' => false,
            'panic_button' => false,
            'qr_security_scanner' => false,
            'advanced_reports' => false,
            'bulk_operations' => false,
        ],
    ],

    'standard' => [
        'name' => 'Plan Estándar',
        'price' => 349000,
        'max_units' => 80,
        'features' => [
            // Hereda todo de basic
            'correspondence' => true,
            'announcements' => true,
            'support_tickets' => true,
            'apartment_management' => ['level' => 'complete'],
            'resident_management' => ['level' => 'complete'],
            'basic_administration' => true,
            'analytics_dashboard' => ['level' => 'intermediate'],
            'access_control' => ['level' => 'complete'],
            'system_configuration' => true,
            'push_notifications' => true,
            'documents' => ['storage_gb' => 3],

            // Nuevos en Standard
            'maintenance_requests' => ['max_monthly' => 50],
            'financial_reports' => ['level' => 'basic'],
            'expense_approvals' => ['workflow' => 'simple'],
            'institutional_email' => true,
            'internal_messaging' => true,
            'audit_logs' => ['level' => 'basic', 'retention_days' => 30],

            // Marketplace mejorado
            'marketplace_providers' => [
                'enabled' => true,
                'access_level' => 'enhanced',
                'quotations_monthly' => 10,
                'commission_rate' => 0.06,
                'provider_directory' => true,
                'provider_ratings' => 'read_write',
                'direct_contact' => true,
                'payment_integration' => false,
                'quotation_comparison' => true,
                'provider_history' => true,
                'favorites_blacklist' => true,
                'basic_analytics' => true,
            ],

            // Features NO incluidos
            'visitor_management' => false,
            'accounting' => false,
            'reservations' => false,
            'payment_agreements' => false,
            'meeting_minutes' => false,
            'voting' => false,
            'panic_button' => false,
            'qr_security_scanner' => false,
            'advanced_reports' => false,
            'bulk_operations' => false,
        ],
    ],

    'premium' => [
        'name' => 'Plan Premium',
        'price' => 649000,
        'max_units' => 200,
        'features' => [
            // Hereda todo de standard
            'correspondence' => true,
            'announcements' => true,
            'support_tickets' => ['level' => 'complete'],
            'apartment_management' => ['level' => 'advanced'],
            'resident_management' => ['level' => 'advanced'],
            'basic_administration' => true,
            'analytics_dashboard' => ['level' => 'advanced'],
            'access_control' => ['level' => 'advanced'],
            'system_configuration' => true,
            'push_notifications' => true,
            'documents' => ['storage_gb' => 10],
            'maintenance_requests' => ['max_monthly' => 'unlimited', 'preventive' => true],
            'financial_reports' => ['level' => 'complete'],
            'expense_approvals' => ['workflow' => 'two_level'],
            'institutional_email' => true,
            'internal_messaging' => true,
            'audit_logs' => ['level' => 'complete', 'retention_days' => 90],

            // Nuevos en Premium
            'visitor_management' => true,
            'accounting' => true,
            'reservations' => true,
            'payment_agreements' => ['max_installments' => 6],
            'meeting_minutes' => true,
            'voting' => ['annual_limit' => 2],
            'panic_button' => ['level' => 'basic'],
            'qr_security_scanner' => true,
            'advanced_reports' => true,
            'bulk_operations' => true,

            // Marketplace profesional
            'marketplace_providers' => [
                'enabled' => true,
                'access_level' => 'professional',
                'quotations_monthly' => 'unlimited',
                'commission_rate' => 0.04,
                'provider_directory' => true,
                'provider_ratings' => 'full_system',
                'direct_contact' => true,
                'payment_integration' => true,
                'quotation_comparison' => true,
                'digital_tenders' => true,
                'digital_contracts' => true,
                'work_orders' => true,
                'provider_analytics' => true,
                'provider_evaluations' => true,
                'preventive_maintenance' => true,
            ],
        ],
    ],

    'enterprise' => [
        'name' => 'Plan Enterprise',
        'price' => 1280000,
        'max_units' => 'unlimited',
        'features' => [
            // Todos los features sin restricciones
            'correspondence' => true,
            'announcements' => true,
            'support_tickets' => ['level' => 'advanced', 'sla' => true],
            'apartment_management' => ['level' => 'enterprise'],
            'resident_management' => ['level' => 'enterprise'],
            'basic_administration' => true,
            'analytics_dashboard' => ['level' => 'enterprise', 'bi_dashboard' => true],
            'access_control' => ['level' => 'enterprise'],
            'system_configuration' => true,
            'push_notifications' => true,
            'documents' => ['storage_gb' => 50],
            'maintenance_requests' => ['max_monthly' => 'unlimited', 'preventive' => true, 'predictive' => true],
            'financial_reports' => ['level' => 'enterprise'],
            'expense_approvals' => ['workflow' => 'multi_level'],
            'institutional_email' => true,
            'internal_messaging' => true,
            'audit_logs' => ['level' => 'enterprise', 'retention_days' => 365],
            'visitor_management' => ['advanced' => true],
            'accounting' => true,
            'reservations' => ['advanced' => true],
            'payment_agreements' => ['max_installments' => 'unlimited'],
            'meeting_minutes' => true,
            'voting' => ['annual_limit' => 'unlimited'],
            'panic_button' => ['level' => 'advanced', 'integration_24_7' => true],
            'qr_security_scanner' => true,
            'advanced_reports' => ['bi_dashboard' => true],
            'bulk_operations' => true,

            // Marketplace VIP
            'marketplace_providers' => [
                'enabled' => true,
                'access_level' => 'vip',
                'quotations_monthly' => 'unlimited',
                'commission_rate' => 0.02,
                'provider_directory' => true,
                'exclusive_providers' => true,
                'provider_ratings' => 'full_system',
                'direct_contact' => true,
                'payment_integration' => true,
                'quotation_comparison' => true,
                'digital_tenders' => true,
                'reverse_auctions' => true,
                'framework_agreements' => true,
                'digital_contracts' => true,
                'work_orders' => true,
                'provider_analytics' => 'advanced',
                'volume_negotiation' => true,
                'marketplace_api' => true,
                'account_manager' => true,
                'executive_dashboard' => true,
            ],

            // Enterprise exclusives
            'api_access' => true,
            'custom_subdomain' => true,
            'custom_branding' => true,
            'multi_property' => true,
            'dedicated_support' => true,
            'account_manager' => true,
        ],
    ],
];
