apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      acme.cert-manager.io/http01-override-ingress-class: traefik
    creationTimestamp: "2025-10-25T15:30:21Z"
    generation: 3
    name: tavira-tls
    namespace: default
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: tavira-ingress
      uid: bdb8a914-515a-42e3-bfb9-528a632e5683
    resourceVersion: "147699"
    uid: cdaccc16-acb2-42d4-aa52-36d5babac065
  spec:
    dnsNames:
    - tavira.com.co
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: tavira-tls
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2025-10-27T15:23:09Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 3
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-01-25T14:24:38Z"
    notBefore: "2025-10-27T14:24:39Z"
    renewalTime: "2025-12-26T14:24:38Z"
    revision: 2
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"torresdevillacampestre-tls","namespace":"default"},"spec":{"dnsNames":["torresdevillacampestre.tavira.com.co"],"issuerRef":{"kind":"ClusterIssuer","name":"letsencrypt-prod"},"secretName":"torresdevillacampestre-tls"}}
    creationTimestamp: "2025-10-27T15:23:07Z"
    generation: 1
    name: torresdevillacampestre-tls
    namespace: default
    resourceVersion: "147740"
    uid: 59391a21-5b1c-4135-94f3-8285d7c972a6
  spec:
    dnsNames:
    - torresdevillacampestre.tavira.com.co
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: torresdevillacampestre-tls
  status:
    conditions:
    - lastTransitionTime: "2025-10-27T15:23:30Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-01-25T14:24:58Z"
    notBefore: "2025-10-27T14:24:59Z"
    renewalTime: "2025-12-26T14:24:58Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""
