apiVersion: v1
data:
  default.conf: |
    # =============================================================================
    # NGINX Configuration for Laravel/Inertia.js App
    # Optimized for Kubernetes sidecar architecture with proper proxy header handling
    # =============================================================================

    # Map proxy headers with fallback to nginx variables
    # This ensures we use Traefik's headers when available
    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        "" $scheme;
    }

    map $http_x_forwarded_host $forwarded_host {
        default $http_x_forwarded_host;
        "" $host;
    }

    map $http_x_forwarded_port $forwarded_port {
        default $http_x_forwarded_port;
        "" $server_port;
    }

    map $http_x_forwarded_for $forwarded_for {
        default $http_x_forwarded_for;
        "" $remote_addr;
    }

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        root /var/www/html/public;
        index index.php index.html;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;

        # Disable server tokens
        server_tokens off;

        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log warn;

        # Client settings
        client_max_body_size 10M;
        client_body_timeout 60s;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript
                   application/json application/javascript application/xml+rss
                   application/rss+xml font/truetype font/opentype
                   application/vnd.ms-fontobject image/svg+xml;

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        # Static files - cache for 1 year
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            access_log off;
            try_files $uri =404;
        }

        # Deny access to hidden files
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        # Main location - route everything through index.php
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # PHP-FPM processing
        location ~ \.php$ {
            # Security: don't execute PHP files from uploads
            location ~ ^/storage/.*\.php$ {
                deny all;
            }

            fastcgi_split_path_info ^(.+\.php)(/.+)$;

            # Connect to PHP-FPM via localhost (same pod in K8s)
            fastcgi_pass 127.0.0.1:9000;

            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

            include fastcgi_params;

            # Forward proxy headers to PHP
            # Preserve headers from upstream proxy (Traefik) or use nginx variables as fallback
            # This is critical for signed URL validation and multitenancy
            # Override SERVER_NAME to use forwarded host instead of wildcard "_"
            fastcgi_param SERVER_NAME $forwarded_host;
            fastcgi_param HTTP_X_FORWARDED_HOST $forwarded_host;
            fastcgi_param HTTP_X_FORWARDED_PROTO $forwarded_proto;
            fastcgi_param HTTP_X_FORWARDED_FOR $forwarded_for;
            fastcgi_param HTTP_X_FORWARDED_PORT $forwarded_port;

            # Timeouts
            fastcgi_read_timeout 300s;
            fastcgi_send_timeout 300s;

            # Buffer settings
            fastcgi_buffer_size 32k;
            fastcgi_buffers 8 16k;
            fastcgi_busy_buffers_size 32k;

            # Security
            fastcgi_hide_header X-Powered-By;
        }

        # Deny access to sensitive files
        location ~ /\.(env|git|gitignore|gitattributes) {
            deny all;
            access_log off;
            log_not_found off;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"# =============================================================================\n# NGINX Configuration for Laravel/Inertia.js App\n# Optimized for Kubernetes sidecar architecture\n# =============================================================================\n\nserver {\n    listen 80;\n    listen [::]:80;\n    server_name _;\n\n    root /var/www/html/public;\n    index index.php index.html;\n\n    # Security headers\n    add_header X-Frame-Options \"SAMEORIGIN\" always;\n    add_header X-Content-Type-Options \"nosniff\" always;\n    add_header X-XSS-Protection \"1; mode=block\" always;\n    add_header Referrer-Policy \"no-referrer-when-downgrade\" always;\n\n    # Disable server tokens\n    server_tokens off;\n\n    # Logging\n    access_log /var/log/nginx/access.log;\n    error_log /var/log/nginx/error.log warn;\n\n    # Client settings\n    client_max_body_size 10M;\n    client_body_timeout 60s;\n\n    # Gzip compression\n    gzip on;\n    gzip_vary on;\n    gzip_proxied any;\n    gzip_comp_level 6;\n    gzip_types text/plain text/css text/xml text/javascript\n               application/json application/javascript application/xml+rss\n               application/rss+xml font/truetype font/opentype\n               application/vnd.ms-fontobject image/svg+xml;\n\n    # Health check endpoint\n    location /health {\n        access_log off;\n        return 200 \"healthy\\n\";\n        add_header Content-Type text/plain;\n    }\n\n    # Static files - cache for 1 year\n    location ~* \\.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {\n        expires 1y;\n        add_header Cache-Control \"public, immutable\";\n        access_log off;\n        try_files $uri =404;\n    }\n\n    # Deny access to hidden files\n    location ~ /\\. {\n        deny all;\n        access_log off;\n        log_not_found off;\n    }\n\n    # Main location - route everything through index.php\n    location / {\n        try_files $uri $uri/ /index.php?$query_string;\n    }\n\n    # PHP-FPM processing\n    location ~ \\.php$ {\n        # Security: don't execute PHP files from uploads\n        location ~ ^/storage/.*\\.php$ {\n            deny all;\n        }\n\n        fastcgi_split_path_info ^(.+\\.php)(/.+)$;\n\n        # Connect to PHP-FPM via localhost (same pod in K8s)\n        fastcgi_pass 127.0.0.1:9000;\n\n        fastcgi_index index.php;\n        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;\n\n        include fastcgi_params;\n\n        # Timeouts\n        fastcgi_read_timeout 300s;\n        fastcgi_send_timeout 300s;\n\n        # Buffer settings\n        fastcgi_buffer_size 32k;\n        fastcgi_buffers 8 16k;\n        fastcgi_busy_buffers_size 32k;\n\n        # Security\n        fastcgi_hide_header X-Powered-By;\n    }\n\n    # Deny access to sensitive files\n    location ~ /\\.(env|git|gitignore|gitattributes) {\n        deny all;\n        access_log off;\n        log_not_found off;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"tavira"},"name":"tavira-nginx-config","namespace":"default"}}
  creationTimestamp: "2025-10-25T00:19:43Z"
  labels:
    app: tavira
  name: tavira-nginx-config
  namespace: default
  resourceVersion: "70912"
  uid: 278bb0f2-fadb-4a9f-be19-45952b0456cf
