apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"postgres-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: vmi2874420
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-25T15:39:01Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: postgres
    name: postgres-pvc
    namespace: default
    resourceVersion: "45140"
    uid: 8ce316c5-b480-4cfe-b796-a91b0eb64aa4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-8ce316c5-b480-4cfe-b796-a91b0eb64aa4
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"tavira"},"name":"tavira-storage-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: vmi2874420
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-25T14:10:57Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: tavira
    name: tavira-storage-pvc
    namespace: default
    resourceVersion: "40619"
    uid: 0b3cb867-649e-4ac6-8bbf-af9913098953
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-0b3cb867-649e-4ac6-8bbf-af9913098953
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
